(function(){
var threads=window.semdiffAnswers||[];
var targets=new Map();
function key(anchor){return anchor.type+'\u0000'+anchor.group_id+'\u0000'+(anchor.step_id||'')+'\u0000'+(anchor.fragment_id||'')}
function appendInlineMarkdown(host,text){String(text).split(/(`[^`\n]+`)/).forEach(function(part){if(part.length>1&&part[0]==='`'&&part[part.length-1]==='`'){var code=document.createElement('code');code.textContent=part.slice(1,-1);host.append(code)}else host.append(document.createTextNode(part))})}
function markdownContent(content){var root=document.createElement('div');root.className='qa-markdown';var normalized=String(content||'').replace(/\\n/g,'\n');var blocks=normalized.split(/```/);blocks.forEach(function(block,index){if(index%2){var pre=document.createElement('pre');var code=document.createElement('code');code.textContent=block.replace(/^[^\n]*\n?/,'').replace(/\n$/,'');pre.append(code);root.append(pre);return}block.split(/\n{2,}/).forEach(function(paragraph){if(!paragraph)return;var p=document.createElement('p');paragraph.split('\n').forEach(function(line,lineIndex){if(lineIndex)p.append(document.createElement('br'));appendInlineMarkdown(p,line)});root.append(p)})});return root}
function textLine(className,label,content,markdown){var line=document.createElement('div');line.className=className;var marker=document.createElement('span');marker.className='qa-label';marker.textContent=label;line.append(marker,markdown?markdownContent(content):document.createTextNode(String(content).replace(/\\n/g,'\n')));return line}
document.querySelectorAll('.guided-group').forEach(function(group){
  targets.set(key({type:'group',group_id:group.dataset.groupId}),group.querySelector(':scope > .guided-group-summary')||group.querySelector(':scope > summary'));
  group.querySelectorAll('.review-step').forEach(function(step){var summary=step.querySelector(':scope > summary');targets.set(key({type:'step',group_id:group.dataset.groupId,step_id:step.dataset.stepId}),summary);step.querySelectorAll('.fragment-note').forEach(function(note){var id=(note.querySelector('.fragment-note-id')&&note.querySelector('.fragment-note-id').textContent.split(' · ')[0].trim())||'';var file=note.closest('.guided-file');if(id)targets.set(key({type:'fragment',group_id:group.dataset.groupId,fragment_id:id}),file?file.querySelector(':scope > summary'):(note.closest('pre')||note))})})
});
var grouped=new Map();threads.forEach(function(thread){var id=key(thread.anchor);if(!grouped.has(id))grouped.set(id,[]);grouped.get(id).push(thread)});
grouped.forEach(function(items,id){var host=targets.get(id);if(!host)return;var panel=document.createElement('section');panel.className='qa-panel';var list=document.createElement('div');list.className='qa-thread-list';items.forEach(function(thread,index){var article=document.createElement('details');article.className='qa-thread';article.open=true;var heading=document.createElement('summary');heading.className='qa-thread-summary';heading.textContent='Thread '+(index+1)+' · '+thread.turns[0].question;article.append(heading);var body=document.createElement('div');body.className='qa-thread-body';thread.turns.forEach(function(turn){var node=document.createElement('section');node.className='qa-turn';node.append(textLine('qa-question','Q',turn.question),textLine('qa-answer','A',turn.answer,true));body.append(node)});article.append(body);list.append(article)});panel.append(list);host.after(panel)});
})();
